name: 'Do While Not Queued'
description: 'Repetitively execute the specified command until the specified workflow is queued'
inputs:
  command-line:
    description: 'The command to run'
    required: true
  args:
    description: 'Arguments to the command can be listed here, multiple arguments can be separated with argsSeparator'
    required: true
    default: ''
  args-separator:
    description: 'Used to delineate where one argument end and the next starts'
    required: true
    default: ';'
  check-every:
    description: 'Use to control how often it will check see if any item has been queued'
    required: true
    default: "1"
  detail-level:
    description: 'How details the output should be. 0 = None, 1 = Count, 2 = Full'
    required: true
    default: "1"
  workflow:
    description: 'The workflow to look for.  And should be set as workflow: dollar-dollar{{ github.WORKFLOW }}'
    required: true
  max-runs:
    description: 'The max number of times to run the command, set < 1 to just keep going'
    required: true
    default: "1000"
  max-time-seconds:
    description: 'The max number of second to keep checking, set < 1 to just keep going'
    required: true
    default: "3600"  # 1 hour
  GITHUB_TOKEN: 
    description: 'The Token that has read access to Actions REST API.  And should be set as GITHUB_TOKEN: dollar-dollar{{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'aperture'  
  color: 'green'
