name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # First check that the dist is up-to-date
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install dependencies, ncc and build
        run: |
          npm install
          npm i -g @vercel/ncc
          ncc build index.js --license licenses.txt

      - name: Check for changes
        id: git-check
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git status --porcelain
          echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Fail if dist is not up to date
        if: ${{ steps.git-check.outputs.changed != '0' }}
        run: |
          echo "dist is not up to date. Please run the build and commit the changes."
          exit 1

      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
          prefer_branch_releases: true